export const DATA_SUMMARY_TYPE_STRIKES = "DATA_SUMMARY_TYPE_STRIKES";
export const DATA_SUMMARY_TYPE_DOUBLE = "DATA_SUMMARY_TYPE_DOUBLE";
export const DATA_SUMMARY_TYPE_FIRST_BALL_AVERAGE =
  "DATA_SUMMARY_TYPE_FIRST_BALL_AVERAGE";
