export const GAME_ALL = "GAME_ALL";
export const GAME_BAKER = "GAME_BAKER";
export const GAME_TEAM = "GAME_TEAM";
export const GAME_BAKER_MATCH_PLAY = "GAME_BAKER_MATCH_PLAY ";

export const VIEW_OVERALL = "VIEW_OVERALL";
export const VIEW_BY_GAME = "VIEW_BY_GAME";
export const VIEW_BY_INDIVIDUAL = "VIEW_BY_INDIVIDUAL";
export const VIEW_BY_GAME_INDIVIDUAL = "VIEW_BY_GAME_INDIVIDUAL";
export const VIEW_BY_INDIVIDUAL_GAME = "VIEW_BY_INDIVIDUAL_GAME";
