export const PAGE_EVENT_ALL = "PAGE_EVENT_ALL";
export const PAGE_EVENT_SINGLE = "PAGE_EVENT_SINGLE";
export const PAGE_BOWLER_ALL = "PAGE_BOWLER_ALL";
export const PAGE_BOWLER_SINGLE = "PAGE_BOWLER_SINGLE";
