export const SUMMARY_SCORE = "SUMMARY_SCORE";
export const SUMMARY_STRIKES = "SUMMARY_STRIKES";
export const SUMMARY_DOUBLE = "SUMMARY_DOUBLE";
export const SUMMARY_FIRST_BALL_AVE = "SUMMARY_FIRST_BALL_AVE";
